### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [ry00001/hackmud-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by lewisakura** [comment]
https://cat.girlsare.life/9507a7.png @unixorn 

![img](https://cat.girlsare.life/9507a7.png)

**Comment by snightshade** [comment]
@LewisTehMinerz @unixorn i've uploaded the screenshot to the main repo as terminal.png; closing.
